version: '3.8'

services:
  app:
    build:
      context: ./renewable-pitch
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./renewable-pitch:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      STOCK_API_KEY: ${STOCK_API_KEY}
